### ISSUE TITLE
Bug in formatEngineResultStyleA with bad stack

### ISSUE THREAD

**Issue by Javantea** [GregoryCannon/StackRabbit#12]
The server fails when given a difficult board. I was able to get a stack trace from my own server.
```
TypeError: Cannot read properties of null (reading 'evalScore')
    at /home/stack/StackRabbit-git/built/src/server/engine_lookup.js:105:52
    at Array.map (<anonymous>)
    at /home/stack/StackRabbit-git/built/src/server/engine_lookup.js:100:41
    at Array.map (<anonymous>)
    at formatEngineResultStyleA (/home/stack/StackRabbit-git/built/src/server/engine_lookup.js:86:25)
    at Object.engineLookup (/home/stack/StackRabbit-git/built/src/server/engine_lookup.js:46:12)
    at RequestHandler.handleEngineLookup (/home/stack/StackRabbit-git/built/src/server/request_handler.js:402:47)
    at RequestHandler.routeRequest (/home/stack/StackRabbit-git/built/src/server/request_handler.js:136:30)
    at /home/stack/StackRabbit-git/built/src/server/app.js:48:40
    at Layer.handle [as handle_request] (/home/stack/StackRabbit-git/node_modules/express/lib/router/layer.js:95:5)
```

Request:
https://stackrabbit.herokuapp.com/engine?board=0000000X000000000X0000XXX0XX0X00XXX00X0X0X0XXXXX0X0XXXXXXXXX0XXXXXX0XX00XXXXX0XX00000XXXXX00000XXXXX000000XXXX00XXXXX000X0XXX00000X0XXX00000X0XX000000XXX000XXX0XX000XXXX0XXX0XXXXX0XXXXXXXXX0XXXXXXXXX0&currentPiece=S&nextPiece=O&level=18&lines=126&reactionTime=0&inputFrameTimeline=X..

**Comment by Warhols** [comment]
I'm still having issues getting the server up and running. The readme is pretty vague. Getting the following:
`Error: Type of "name" (string)  is not supported. Use objects or arrays of objects.
    at /usr/local/lib/node_modules/json-server/lib/server/router/index.js:77:11
    at /usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:3032:24)
    at /usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:9410:14)
    at /usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:4430:28
    at arrayReduce (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:697:21)
    at baseWrapperValue (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:4429:14)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:9114:14)
    at Object.module.exports [as router] (/usr/local/lib/node_modules/json-server/lib/server/router/index.js:78:6)
`

**Comment by Javantea** [comment]
Please create a new issue for your problem. This issue is the wrong place to discuss your issue.
