### ISSUE TITLE
Got response: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by preethamrn** [GregoryCannon/StackRabbit#14]
I'm running the server using `npm run start` and the program appears to build and run fine however when I try running the `httpTest.lua` script I get the error
```
Got response: Cannot read properties of undefined (reading 'split')
```

It appears to be coming from the following stack trace.
```
localhost:3000/precompute/00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000001101110000110/L/J/18/0/0/0/0/0/0/X..../false
TypeError: Cannot read properties of undefined (reading 'split')
    at parseUrlArguments (/home/user/projects/StackRabbit/built/src/server/request_parser.js:62:27)
    at RequestHandler.routeRequest (/home/user/projects/StackRabbit/built/src/server/request_handler.js:109:52)
    at /home/user/projects/StackRabbit/built/src/server/app.js:48:40
    at Layer.handle [as handle_request] (/home/user/projects/StackRabbit/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/user/projects/StackRabbit/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/user/projects/StackRabbit/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/user/projects/StackRabbit/node_modules/express/lib/router/layer.js:95:5)
    at /home/user/projects/StackRabbit/node_modules/express/lib/router/index.js:281:22
    at param (/home/user/projects/StackRabbit/node_modules/express/lib/router/index.js:354:14)
    at param (/home/user/projects/StackRabbit/node_modules/express/lib/router/index.js:365:14)
Full request: 1.81ms
```

I'm not sure what might be causing this

**Comment by Croios7** [comment]
I have the same problem. I managed to run server, but this split is making me problems. Also, maybe I should integrate cpp modules, but I dont know how
